# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Booster
                                 A QGIS plugin
 This plugin allows to sync the monday database with the qgis data visualization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-06
        copyright            : (C) 2024 by Paul Poissonnet - Wattmen
        email                : paul.poissonnet@wattmen.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Booster class from file Booster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .booster import Booster
    return Booster(iface)
